- hosts: localhost
  pre_tasks:
    - name: "set shell type zsh"
      set_fact:
        shell_name: "zsh"
      when: shell_rc == ".zshrc"
      tags: always

    - name: "set shell type bash"
      set_fact:
        shell_name: "bash"
      when: shell_rc == ".bash_profile"
      tags: always

  tasks:
    - name: message
      debug:
        msg: "{{ansible_env.HOME}}"
  roles:
    - general_software
    - kubernetes
    - aws_cli
    - starship
    - golang
