# Inserts a blank line between shell prompts
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[battery]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
format = '[ns: \($namespace\)](dimmed green) '
disabled = false

[lua]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
format = '[(\($virtualenv\) )]($style)'
symbol = ""

[rlang]
disabled = true

[red]
disabled = true

[scala]
disabled = true

[terraform]
format = "[$version]($style) "

[username]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true