---
- name: Install Kubectl
  community.general.homebrew:
    name: kubectl
  tags:
    - kubernetes
    - kubectl

- name: Install Helm
  community.general.homebrew:
    name: helm
  tags:
    - kubernetes
    - helm

- name: Install Kubectl extras
  community.general.homebrew:
    name: "{{ item }}"
  loop:
    - kubectx
    - derailed/k9s/k9s
    - operator-sdk
  tags:
    - kubernetes
    - kube-extras

- name: add auto_completion
  ansible.builtin.lineinfile:
    path: "{{ansible_env.HOME}}/{{ shell_rc }}"
    line: "source <(kubectl completion {{ shell_name }})"
    state: present
  tags: kubernetes

- name: shell_rc alias
  ansible.builtin.lineinfile:
    path: "{{ansible_env.HOME}}/{{ shell_rc }}"
    line: "{{ item }}"
    state: present
  loop:
    - "alias k='kubectl'"
    - "complete -F __start_kubectl k"
    - "alias kg='kubectl get'"
    - "alias kgpo='kubectl get pod'"
    - "alias ka='kubectl apply'"
    - "alias kaf='kubectl apply --recursive -f'"
    - "alias kd='kubectl delete'"
    - "alias kdf='kubectl delete -f'"
    - "alias klog='kubectl logs'"
    - "alias klogf='kubectl logs -f'"
    - "alias kubens='kubectl ns'"
  tags:
    - kubernetes

- name: remove complete line if zsh
  ansible.builtin.lineinfile:
    path: "{{ansible_env.HOME}}/{{ shell_rc }}"
    line: "complete -F __start_kubectl k"
    state: absent
  when: shell_name == "zsh"
  tags:
    - kubernetes

- name: Install Argo Cli
  block:
    - name: Download Argo Cli
      get_url:
        url: "https://github.com/argoproj/argo-workflows/releases/download/{{ argo_version}}/argo-darwin-amd64.gz"
        dest: /tmp/argo-darwin-amd64.gz
        validate_certs: "{{ validate_certs }}"

    - name: Uncompress
      command:
      args:
        cmd: "gunzip /tmp/argo-darwin-amd64.gz"
        creates: /tmp/argo-darwin-amd64

    - name: Copy to path
      copy:
        src: /tmp/argo-darwin-amd64
        dest: /usr/local/bin/argo
        mode: a+x

    - name: Clean Up
      file:
        path: /tmp/argo-darwin-amd64
        state: absent
  tags:
    - argo
    - never
