---
- name: Install CLI
  block:
    - name: Download awscliv2 installer.
      get_url:
        url: https://awscli.amazonaws.com/AWSCLIV2.pkg
        dest: /tmp/AWSCLIV2.pkg
        validate_certs: "{{ validate_certs }}"

    - name: Run the installer.
      command:
      args:
        cmd: "installer -pkg /tmp/AWSCLIV2.pkg -target /"
      become: true
      register: aws_install

    - name: Clean up
      ansible.builtin.file:
        path: /tmp/AWSCLIV2.pkg
        state: absent

    - name: "Show installer output."
      debug:
        var: aws_install
        verbosity: 2

  tags:
    - aws_cli
    - never

- name: Install saml2aws
  community.general.homebrew:
    name: saml2aws
  tags:
    - saml2aws
    - never
