---
- name: Install CLI
  block:
    - name: Download awscliv2 installer.
      get_url:
        src: https://awscli.amazonaws.com/AWSCLIV2.pkg
        dest: /tmp/AWSCLIV2.pkg

    - name: Run the installer.
      command:
      args:
        cmd: "installer -pkg AWSCLIV2.pkg -target /"
        creates: /usr/local/bin/aws
      become: true
      register: aws_install

    - name: Clean up
      ansible.builtin.file:
        path: /tmp/AWSCLIV2.pkg
        state: absent

    - name: "Show installer output."
      debug:
        var: aws_install
        verbosity: 2
  tags: aws_cli