---
- name: Install General
  community.general.homebrew:
    name: "{{ item }}"
  loop:
    - wget
    - tree
    - warrensbox/tap/tfswitch
    - jq
    - coreutils
  tags:
    - general

- name: Install openjdk
  block:
    - name: openjdk install
      community.general.homebrew:
        name: openjdk

    - name: Link file
      ansible.builtin.file:
        src: /usr/local/opt/openjdk/libexec/openjdk.jdk
        dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
        state: link
  tags: java

- name: Install git bash completion
  block:
    - name: Brew install
      community.general.homebrew:
        name: bash-completion

    - name: add bash_profile line
      ansible.builtin.lineinfile:
        path: "{{ansible_env.HOME}}/{{ shell_rc }}"
        line: '[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"'
        state: present
  tags:
    - git-bash-completion
  when: shell_rc == ".bash_profile"
